### ISSUE TITLE
Issue using this lib with Travis-CI

### ISSUE THREAD

**Issue by Nhoya** [gotmc/libusb#5]
Hey there, we use this library in our project but we have some troubles integrating it in Travis-CI, this is the  script
```
language: go

go:
  - 1.8.x
  - master

os:
  - linux
dist: trusty
addons:
        apt:
                packages:
                        libusb-1.0-0-dev
                        libusb-1.0-0
install:
  - go get -v github.com/gotmc/libusb
  - go build

script:
  - go tool vet -v -all ./
```
The error is 
`could not determine kind of name for C.LIBUSB_TRANSFER_TYPE_BULK_STREAM`
